apiVersion: v1
kind: Service
metadata:
  name: app-backend-python
  namespace: app-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: app-backend-python